### ISSUE TITLE
Dep.target.addDep(this) 中 this 的值

### ISSUE THREAD

**Issue by sunorry** [numbbbbb/read-vue-source-code#3]
在 `04-dynamic-data-observer-dep-and-watcher.md` 中解释 `Watcher` 中的 `get` 时：

> inside depend(), it calls Dep.target.addDep(this), here this is _data's dep, it's stored at vm._data.__ob__.dep

这里的 `this` 应该是 `name: 'foo'` 的，而不是 `_data` 的。

1. 在 `new Observer` 时 `dep` 为 `_data` 的
2. 在 `defineReactive` 时 `dep` 为其中的 `foo`

如果我理解的有错误，请指正。

**Comment by numbbbbb** [comment]
我看了一下，这里我确实写错了，你指出的问题是存在的。
不过你说的这两条，也有一些问题。
简单来说，defineReactive是遍历了一遍data的所有属性，对每个属性做一个observe操作，如果属性对应的值不是字面量（字符串、数值、布尔值），就递归地对属性值做observe操作。
只有做过observe操作的属性，才会有Observer，也才会有dep。在这个例子里，被observe的是name属性，这里的的dep属于name对应的Observer。
dep指向的并不是属性名，也不是属性对应的值，而是这个属性对应的Observer里面定义的一个值。
这里的this，引用的是name对应的Observer里的dep，也就是`vm._data.name.__ob__.dep`。

**Comment by sunorry** [comment]
@numbbbbb 前面说的都同意，最后一句我认为不对。

> 也就是`vm._data.name.__ob__.dep`。

`name` 属性是没有 `__ob__` 的，只有值是 `Object` 的时候才会调用 `def(value, '__ob__', this)` 方法。

目前文档被修改成：

> here this is name's `dep`, it's stored at `vm._data.name.__ob__.dep`

`dep` 并没有存储在 `vm._data.name.__ob__.dep`，就是调用了 `depend`，`this` 就是上面声明的 `dep`。

一个 demo 便可证伪。

```js
window.ddd = new Vue({
  el: '#app',
  data: {
      name: 'github'
  }
})
```

`ddd._data.name.__ob__.dep` 是不存在的。

如果我理解的有错误，请指正。

**Comment by numbbbbb** [comment]
你说得对，name确实不能被observe，被observe的应该是data指向的Object，也就是{name: 'foo'}。
dep应该是存储在`ddd._data.__ob__.dep`。
