### ISSUE TITLE
Dep和observer那里的说明有些看不懂

### ISSUE THREAD

**Issue by vaxilicaihouxian** [numbbbbb/read-vue-source-code#4]
> inside depend(), it calls Dep.target.addDep(this), here this refers to the dep property of object _data's observer, it's stored at vm._data.__ob__.dep

这里的说明有些疑惑，dep使用的都是闭包内的实例，没有使用__ob__.dep啊（只有数组才会用到__ob__.deb 吧，因为数组没有setter getter)

针对示例中的内容_data.name 这个是对象吧，不是数组，所以不存在存储到__ob__.dep的说法吧？

**Comment by numbbbbb** [comment]
你说得对，这里我有点搞混了。
defineReactive是把对象的一个属性转换成reactive。但是如果属性的值是非字面量，也就是对象（包括正常的对象、数组、函数等等），改变对象内部的值并不会触发属性的setter（因为属性存储的只是对象引用），所以才加了一个Observer，来解决这个问题。
具体到dep上面，属性的dep就是你说的，闭包里的局部变量。如果属性的值是对象，那才是引用`__ob__.dep`，这个是在observe值的时候创建。
多谢你的提醒，帮助我加深了理解，我会修改文章内容。

**Comment by numbbbbb** [comment]
我在修改的过程中发现，上面的解释还是有点问题，我加了一个例子和一张图到文章里，你可以再看下。
准确的说，在我们讨论的这个例子里，`vm._data`被`defineReactive`转换成了reactive属性，它的值实际上是一个对象，所以被`observe`加上了`__ob__`属性，其中又有一个dep。
换句话说，在我们讨论的例子中，`childOb`是存在的，所以getter里调用了两次`depend()`。第一次是你说的这次，this指向的是reactive属性`_data`的dep，也就是上面const的那个。第二次是`childOb.dep.depend()`，这里的this就是被observe的`childOb`自己的dep，也就是`childOb.__ob__.dep`。

**Comment by vaxilicaihouxian** [comment]
是的 _data就是一个对象 最开始defineReactive的时候会调用childOb.dep.depend (收集所有用户添加的"data"属性)

**Comment by jo0ger** [comment]
对于文章里的这个例子，我不太理解为什么 childOb 存在
```js
{
  data: {
    name: 'foo'
  },
  computed: {
    newName () {
      return this.name + 'new!'
    }
  }
}
```
> inside the getter, it calls dep.depend()
> inside depend(), it calls Dep.target.addDep(this), here this refers to the const dep, it's _data's dep
> then it calls childOb.dep.depend() which add the dep of childOb to our target. Notice this time the this of Dep.target.addDep(this) refers to childOb.__ob__.dep

在 `this._data['name']` 的 getter 里， dep 是闭包内的 dep 而不是 `_data.__ob__`，而且 name 的 getter 里的 `childOb` 是 `undefined`，所以是不会执行 `childOb.dep.depend()` 的

据我所理解，getter 里的 childOb.dep.depend 是有如下两个场景需要用到：
1. 对于普通 object：调用 $set 或 $delete 给对象动态添加或删除属性时候，是会 触发 `object.__ob__.dep.notify() `的
2. 对于数组：调用数组的几个重写的方法，也是会触发 `array.__ob__.notify()` 的
如果在 getter 里不执行 childOb.dep.depend，那么这两场景下触发 notify 其实是不会触发 watcher 的
