### ISSUE TITLE
Share code with code, not images

### ISSUE THREAD

**Issue by vvscode** [numbbbbb/read-vue-source-code#6]
I would be glad to translate your notes and it would be perfect if you share code as code snippets, not as screenshots.

Thanks in advance

**Comment by numbbbbb** [comment]
Good advice! I have replaced all code screenshots with code snippets. 

Just keep several Sublime search result screenshots. I use that type of screenshots to show "what I see" in my Sublime window, so it doesn't make sense to use code snippet. But I attach the code after I "double-click the search result and jump into the file".

Besides, if you publish the translation please send me a link. I'm really looking forward to seeing that!
